import { describe, expect, test } from "bun:test";
import { existsSync } from "node:fs";
import { fileURLToPath } from "node:url";

describe("admin navigation", () => {
  test("contains only current pages and no legacy aliases", async () => {
    const app = await Bun.file(new URL("../src/web/app.imba", import.meta.url)).text();
    const auth = await Bun.file(new URL("../src/web/auth.imba", import.meta.url)).text();
    const shell = await Bun.file(new URL("../src/web/shell.imba", import.meta.url)).text();
    const store = await Bun.file(new URL("../src/web/store.imba", import.meta.url)).text();
    const home = await Bun.file(new URL("../src/web/home.imba", import.meta.url)).text();
    const connections = await Bun.file(new URL("../src/web/connections.imba", import.meta.url)).text();
    const protocols = await Bun.file(new URL("../src/web/protocols.imba", import.meta.url)).text();
    const routes = await Bun.file(new URL("../src/web/routes.imba", import.meta.url)).text();
    const dialogs = await Bun.file(new URL("../src/web/dialogs.imba", import.meta.url)).text();
    const security = await Bun.file(new URL("../src/web/security.imba", import.meta.url)).text();
    const avatars = await Bun.file(new URL("../src/web/avatar-picker.imba", import.meta.url)).text();

    expect(store).toContain("['/', '/connections', '/protocols', '/routes', '/journal', '/access', '/settings', '/login', '/onboarding']");
    expect(app).not.toContain("path == '/setup'");
    expect(store).not.toContain("'/setup'");
    expect(auth).toContain("window.location.assign(onboarding)");
    expect(auth).toContain("credential.authenticatorAttachment == 'cross-platform'");
    expect(auth).toContain("t('auth.remote_hint')");
    expect(app).toContain("window.location.pathname.startsWith('/admin') and params.get('preview') == 'setup'");
    expect(app).toContain("store.dialog == 'passkey'");
    for (const legacy of ["path.startsWith('/traffic')", "path.startsWith('/system')", "path.startsWith('/profile')"]) {
      expect(store).not.toContain(legacy);
    }
    expect(store).not.toContain("Outpost · Трафик");
    expect(store).not.toContain("Outpost · Система");
    expect(shell).not.toContain("outpost-traffic");
    expect(shell).not.toContain("outpost-system store");
    expect(shell).toContain("outpost-connections");
    expect(shell).toContain("outpost-protocols");
    expect(shell).toContain("overflow-x: hidden");
    expect(shell).toContain("get update? do store.data.system.updates.available");
    expect(shell).toContain('<span.notice aria-hidden="true">');
    expect(shell).toContain("tag outpost-mobile-menu");
    expect(shell).toContain("grid-template-columns: repeat(6, minmax(0, 1fr))");
    expect(shell).toContain("nav, .sidebar-footer display: contents");
    expect(shell).toContain(".utility-nav display: none");
    expect(shell).toContain("calc(64px + env(safe-area-inset-bottom))");
    expect(shell).not.toContain(".brand, .sidebar-footer display: none");
    const index = await Bun.file(new URL("../public/index.html", import.meta.url)).text();
    expect(index).toContain("viewport-fit=cover");
    expect(app).not.toContain("./traffic.imba");
    expect(app).not.toContain("./system.imba");
    for (const action of ["Изменить аватар", "Свернуть", "Выберите аватар"]) {
      expect(dialogs).toContain(action);
    }
    expect(dialogs).not.toContain("Известный человек");
    expect(avatars.indexOf("avatar-person")).toBeLessThan(avatars.indexOf("avatar-group"));
    expect(avatars).toContain("Фильтры аватаров");
    expect(routes).toContain("@click.stop=routes.drop(rule.id)");
    expect(routes).toContain("def reset");
    expect(routes).toContain("removing = new Set");
    expect(routes).toContain("disabled=busy @click.stop=routes.drop(rule.id)");
    expect(routes).toContain("<outpost-ruleset-banner store=store>");
    expect(routes).toContain("'/api/v1/rulesets/refresh'");
    expect(routes).toContain("routes.rulesets.delivery");
    expect(routes).toContain(".geo-control gc:2 gtc:1fr justify-items:start ta:left g:10px");
    expect(routes).toContain("outpost-action-picker grid-column:4; grid-row:1; width:34px; margin-top:0");
    expect(routes).toContain("PROXY: 'arrows-left-right'");
    expect(routes).toContain("<outpost-icon.glyph name=glyph>");
    expect(routes).toContain("<outpost-icon.option-glyph name=(glyphs[item.id] or 'prohibit')>");
    expect(routes).toContain(".option-label miw:0 white-space:nowrap");
    expect(routes).toContain("&.compact .glyph d:block fs:18px");
    expect(routes).toContain("&.compact .trigger > .dot d:none");
    expect(routes).toContain("&.compact .trigger > .label d:none");
    expect(routes).toContain("&.compact .caret d:none");
    expect(routes).toContain("&.system grid-template-columns:22px 32px minmax(0,1fr) 34px");
    expect(routes).toContain(".footer-actions g:6px gtc:minmax(0,1.35fr) minmax(0,.9fr)");
    expect(routes).toContain(".footer-actions .outpost-button h:40px miw:0 g:5px p:0 7px fs:11px white-space:nowrap");
    expect(routes).not.toContain("remove = null");
    expect(routes).not.toContain("remove=remove update=update");
    expect(protocols).toContain(".engine-actions gc:4 gr:1");
    expect(protocols).toContain(".engine-connection gc:3 / -1 gr:2 g:3px fs:clamp(8px,2.5vw,10px) lh:1.2 flex-wrap:nowrap white-space:nowrap");
    expect(home).toContain('Math.max(0, Math.min(100, usage(connection) / maximum * 100))');
    expect(home).toContain('<div.bar><span [w:{scale(connection)}%]>');
    expect(home).toContain(".usage d:grid gc:1 / -1 gr:2 gtc:minmax(0,1fr) 70px");
    expect(home).toContain("pl:46px");
    expect(home).not.toContain('style="width:{fmt.percent');
    expect(home).toContain("<span> t('Активность')");
    expect(home).toContain(".metrics gtc:repeat(3, minmax(0,1fr))");
    expect(home).toContain("&.network gc:1 / -1");
    expect(home).toContain("<small> row.detail");
    expect(home).toContain(".metric small mih:13px");
    expect(home).toContain("header h2 strong fs:19px white-space:nowrap");
    expect(home).toContain(".totals strong fs:12px fw:650");
    expect(home).toContain(".period order:-1");
    expect(home).toContain(".period summary jc:space-between");
    expect(home).toContain('<span.activity .online=fmt.connectionOnline(connection)');
    expect(home).not.toContain("<span> t('Последняя активность')");
    expect(home).not.toContain("<span> t('Статус')");
    expect(connections).toContain('<outpost-icon name="dots-three">');
    expect(connections).toContain("<global @click.capture.outside=close @keydown.esc=close>");
    expect(connections).toContain("above = trigger.bottom + height + 8 > window.innerHeight");
    expect(connections).toContain(".connection-menu.above menu t:auto b:calc(100% + 7px)");
    expect(connections).toContain(".connection-row miw:0 mih:86px px:20px rd:12px");
    expect(connections).toContain(".summary flw:nowrap g:10px fs:12px");
    expect(connections).toContain(".page-top .header-action fl:0 0 42px mt:28px");
    expect(connections).toContain(".traffic gc:2 / 4 gr:2 d:grid");
    expect(connections).toContain('<div.traffic-bar aria-hidden="true"><span [w:{scale(connection)}%]>');
    expect(connections).toContain(".row-actions gc:3 gr:1 jc:flex-end");
    expect(connections).toContain(".table-action s:36px d:grid jai:center g:0 px:0");
    expect(connections).toContain(".table-action span d:none");
    expect(connections).toContain("aria-label=t('Подписка') title=t('Подписка')");
    expect(connections).not.toContain("<details.connection-menu>");
    expect(connections).toContain('"/api/v1/connections/{connection.id}/suspend"');
    expect(connections).toContain('"/api/v1/connections/{connection.id}/resume"');
    expect(connections).toContain('disabled=!!connection.suspended_at @click.stop=(do use(connection))');
    expect(connections).toContain("t('connection.edit')");
    expect(connections).toContain("t('connection.delete')");
    expect(dialogs).toContain("t('connection.delete_title')");
    expect(dialogs).not.toContain("connections.note");
    expect(security).toContain("t('access.methods.title')");
    expect(security).toContain("authenticatorAttachment: 'platform'");
    expect(security).toContain("t('passkey.add.warning')");
    expect(existsSync(fileURLToPath(new URL("../src/web/traffic.imba", import.meta.url)))).toBeFalse();
    expect(existsSync(fileURLToPath(new URL("../src/web/system.imba", import.meta.url)))).toBeFalse();
    expect(existsSync(fileURLToPath(new URL("../src/web/people.imba", import.meta.url)))).toBeFalse();
    expect(existsSync(fileURLToPath(new URL("../src/web/proxies.imba", import.meta.url)))).toBeFalse();
  });

  test("refreshes after every SSE reconnect without blocking the 30 second polling fallback", async () => {
    const app = await Bun.file(new URL("../src/web/app.imba", import.meta.url)).text();
    const store = await Bun.file(new URL("../src/web/store.imba", import.meta.url)).text();
    const shell = await Bun.file(new URL("../src/web/shell.imba", import.meta.url)).text();
    const journal = await Bun.file(new URL("../src/web/journal.imba", import.meta.url)).text();

    expect(store).toContain("loading = initial");
    expect(store).toContain("while pending");
    expect(store).toContain("load! if pending");
    expect(store).toContain("new window.EventSource('/api/v1/dashboard/events')");
    expect(store).toContain("\t\tsource.addEventListener 'ready', do self.load!");
    expect(store).toContain("window.setInterval(tick, 30000)");
    expect(store).toContain("window.document.hidden");
    expect(store).toContain("stale = issue.message");
    expect(store).toContain("self.expire! if response.status == 401");
    expect(store).toContain("return payload.message if payload and payload.message");
    expect(store).toContain("changed! if refresh");
    expect(store).toContain("const result = await api(method, url, body)\n\t\t\tawait load!\n\t\t\treturn result");
    expect(app).toContain("store.start!");
    expect(shell).toContain("revision=store.data.revision");
    expect(journal).toContain("@observable revision = 0");
    expect(journal).toContain("@autorun def follow");
    expect(journal).toContain("return if current == seen");
    expect(journal).toContain(".inspect d:block px:0");
    expect(journal).toContain(".body py:14px px:12px");
    expect(journal).toContain(".context time fl:0 0 100%");
    expect(journal).toContain(".context i d:none");
  });

  test("keeps application update progress in the confirmation dialog across reloads", async () => {
    const store = await Bun.file(new URL("../src/web/store.imba", import.meta.url)).text();
    const settings = await Bun.file(new URL("../src/web/settings.imba", import.meta.url)).text();
    const dialogs = await Bun.file(new URL("../src/web/dialogs.imba", import.meta.url)).text();

    expect(store).toContain("item.kind == 'update.apply'");
    expect(store).toContain("data.system.updates.status == 'preparing'");
    expect(store).toContain("window.setTimeout(tick, 1000)");
    expect(settings).toContain("get applying?");
    expect(settings).toContain("operation.status == 'failed'");
    expect(settings).toContain("settings.update.completed");
    expect(settings).not.toContain("<progress.update-progress");
    expect(settings).toContain("<span> t('settings.update.check')");
    expect(settings).toContain('<outpost-icon name="arrows-clockwise" .checking=(busy == \'check\')>');
    expect(settings).toContain(".system-action outpost-icon.checking animation:spin");
    expect(settings).not.toContain("busy == 'check' ? 'spinner-gap' : 'arrows-clockwise'");
    expect(settings).toContain("<button.system-action.install");
    expect(settings).toContain('<span.notice aria-hidden="true">');
    expect(settings).toContain("status: 'failed', ready: false, error: issue.message");
    expect(settings).not.toContain("'/api/v1/rulesets/refresh'");
    expect(settings).not.toContain("rulesets.version");
    expect(dialogs).toContain("store.hold = true");
    expect(dialogs).toContain("item.id == operation.id");
    expect(dialogs).toContain('<progress value=progress max="100" aria-label=stage>');
    expect(dialogs).toContain(".connect-modal .modal-actions@!500 flw:nowrap g:6px");
    expect(dialogs).toContain(".connect-modal .modal-actions .outpost-button@!500 h:42px miw:0 g:6px px:10px fs:13px white-space:nowrap");
    expect(dialogs).toContain('<span.mobile-count aria-hidden="true"> "+{secondary.length}"');
    expect(dialogs).toContain(".app-toolbar@!500 flw:nowrap ai:center g:6px p:10px 12px");
    expect(dialogs).toContain(".app-choice span d@!500:none");
    expect(dialogs).toMatch(/\n(\t+)<div\.platform-select>\n\1\t<button\.platform-trigger/);
    expect(dialogs).toMatch(/\n(\t+)for item in primary\n\1\t<button\.app-choice/);
    expect(dialogs).toMatch(/\n(\t+)<div\.more-picker>\n\1\t<button\.more-trigger/);
    expect(dialogs).toContain("stage = t(current.message) if current.message");
    expect(dialogs).toContain("window.location.reload!");
  });
});
