// Generated locale catalog.
export const semantic = {
  "en": {
    "app.name": "Outpost",
    "title.setup": "Initial Setup",
    "title.onboarding": "Access Configuration",
    "title.login": "Login",
    "title.access": "Access",
    "title.settings": "Panel Settings",
    "title.settings_short": "Settings",
    "title.overview": "Overview",
    "error.request": "Request Failed",
    "error.http": "The server is temporarily unavailable (HTTP {status})",
    "settings.certificate.until": "Until {date}",
    "settings.update.check": "Check",
    "settings.update.upgrade": "Update",
    "settings.update.retry": "Try again",
    "settings.update.loading": "Preparing…",
    "settings.update.working": "Updating…",
    "settings.update.checking": "Checking for updates…",
    "settings.update.preparing": "Downloading and verifying signature…",
    "settings.update.confirm": "Confirm installation of this version.",
    "settings.update.whats_new": "What's new in version {version}",
    "settings.update.notes_fallback": "Fixes and improvements without a separate description.",
    "settings.update.installing": "Installing version {version}…",
    "settings.update.restarting": "Restarting the server and verifying version {version}…",
    "settings.update.completed": "Update installed",
    "settings.update.failed": "Could not install the update",
    "settings.update.current": "Latest version installed",
    "settings.update.available": "Version {version} is available",
    "settings.update.unchecked": "Updates have not been checked yet",
    "settings.update.channel": "Update channel",
    "settings.update.channel_hint": "Stable versions or pre-release candidates",
    "settings.update.channel.stable": "Stable versions",
    "settings.update.channel.candidate": "Release candidates",
    "settings.update.restart_wait": "The server did not return in time after the update",
    "operation.update_verifying": "Verifying the update signature and contents…",
    "operation.update_snapshotting": "Creating a data snapshot…",
    "operation.update_installing": "Installing the new version…",
    "operation.update_restarting": "Restarting Outpost…",
    "operation.update_readiness": "Checking that the new version is ready…",
    "nav.home": "Home",
    "nav.connections": "Connections",
    "nav.routes": "Routes",
    "nav.protocols": "Protocols",
    "role.owner": "Owner",
    "action.addConnection": "New Connection",
    "action.add": "Add",
    "action.cancel": "Cancel",
    "action.save": "Save",
    "action.publish": "Publish",
    "action.copy": "Copy link",
    "action.close": "Close",
    "action.restart": "Restart",
    "action.confirm": "Confirm",
    "connections.title": "Connections",
    "connections.subtitle": "Links, traffic and connection activity",
    "connections.empty": "No connections yet. Create the first one.",
    "connections.name": "Name",
    "home.connections": "Connections",
    "overview.title": "Overview",
    "overview.subtitle": "Server health and network usage",
    "overview.users": "Users",
    "overview.events": "Recent Events",
    "home.infrastructure": "Infrastructure",
    "home.works": "Running",
    "home.online": "Online",
    "routes.title": "Routes",
    "routes.subtitle": "Define which services go directly, through a proxy, or are blocked",
    "routes.add": "Add Rule",
    "routes.draft": "Unpublished changes exist",
    "routes.published": "Published",
    "routes.revision": "Revision",
    "routes.action": "Action",
    "routes.matcher": "Type",
    "routes.value": "Domain, network or list",
    "routes.system": "System",
    "routes.user": "User",
    "routes.direct": "Direct",
    "routes.proxy": "Via proxy",
    "routes.block": "Block",
    "system.log": "Log",
    "journal.eyebrow": "System",
    "journal.title": "Journal",
    "journal.subtitle": "Server events and panel changes",
    "journal.search": "Search logs",
    "system.active": "Running",
    "system.unknown": "Unknown status",
    "engines.eyebrow": "SYSTEM",
    "engines.title": "Protocols",
    "engines.subtitle": "Technologies, versions, and connection configurations",
    "engines.healthy": "Both engines are running",
    "engines.attention": "One engine requires attention",
    "engines.engine": "Engine",
    "engines.state": "Status",
    "engines.version": "Version",
    "engines.connection": "Connection",
    "engines.configuration": "Configuration",
    "engines.actions": "Actions",
    "engines.configure": "Configure",
    "engines.updates": "Engine updates",
    "engines.pinned": "Pinned versions for stability",
    "engines.integrity": "SHA-256 integrity check",
    "engines.no_updates": "No updates available",
    "engines.updates_available": "Updates available",
    "engines.current_versions": "Current versions are up to date",
    "engines.checked": "Versions checked just now",
    "engines.check": "Check versions",
    "engines.checking": "Checking...",
    "engines.recent": "Recent configurations",
    "engines.baseline": "baseline",
    "engines.published": "Published",
    "engines.history": "View History",
    "engines.history_title": "Configuration History",
    "engines.history_hint": "Latest published revisions of Hysteria 2 and Xray.",
    "engines.history_empty": "No custom revisions yet — using default configurations.",
    "engines.note": "Changes are first verified, then applied with automatic rollback on error.",
    "auth.badge": "Owner Panel",
    "auth.title": "Welcome back",
    "auth.subtitle": "Confirm login with Touch ID, Face ID or this device's passkey.",
    "auth.button": "Continue",
    "auth.wait": "Waiting for confirmation…",
    "auth.secure": "Passkey is not sent to the server and remains in your device's keyring.",
    "auth.recovery.title": "No access to passkey?",
    "auth.recovery.subtitle": "Run the recovery command on the server. It will terminate active sessions and open a protected access recovery flow.",
    "auth.story.badge": "Personal Space",
    "auth.story.title": "Your Server, Your Rules.",
    "auth.story.subtitle": "Manage connections for loved ones, routes, and traffic from a single calm panel.",
    "auth.story.transfer": "Transfer settings to another server",
    "auth.story.protocols": "Supports Xray and Hysteria 2",
    "auth.story.clients": "Easy client connection",
    "auth.story.web": "All management via web interface",
    "auth.story.speed": "High speed with no extra load",
    "auth.host": "Panel address",
    "auth.host.copy": "Copy panel address",
    "auth.host.copied": "Address copied",
    "setup.story.badge": "Server installed",
    "setup.story.title": "First launch",
    "setup.story.subtitle": "Select a permanent address. Buying a domain is optional—you can use a free one.",
    "setup.story.running": "Outpost running",
    "setup.story.secure": "Temporary HTTPS connection secured",
    "setup.story.browser": "The rest is configured in the browser",
    "setup.host": "Temporary address",
    "setup.badge": "Dashboard preparation",
    "setup.configured.badge": "Initial setup complete",
    "setup.configured.title": "This server is already configured",
    "setup.configured.done": "If you configured it, use the permanent dashboard address you selected.",
    "setup.configured.warning": "If you own this VPS but did not configure Outpost, someone else may have done so.",
    "setup.configured.action": "Reinstall the VPS from your hosting control panel, install Outpost again, and open this address immediately. Reinstalling erases the server's data.",
    "setup.domain.title": "Domain connection",
    "setup.domain.subtitle": "Choose how to get a permanent Outpost dashboard address.",
    "setup.domain.free": "Free subdomain",
    "setup.domain.free_hint": "Subdomain on free DNS service",
    "setup.domain.free_detail": "Outpost dashboards can get their own free subdomain without buying your own domain.",
    "setup.domain.recommended": "Recommended",
    "setup.domain.own": "Own domain",
    "setup.domain.own_hint": "A domain under your own control",
    "setup.domain.own_detail": "You can create a subdomain specifically for the Outpost panel on an already purchased domain.",
    "setup.configure.progress": "Step 2 of 3 · Address",
    "setup.free.title": "Free Subdomain",
    "setup.free.subtitle": "Select a service that provides free subdomains. When creating the address, specify your server IP and paste the result below.",
    "setup.own.title": "Connect Your Domain",
    "setup.own.subtitle": "Choose a subdomain for the Outpost panel — e.g., proxy.example.com. Then create an A record for it.",
    "setup.domain.service": "Select Free Subdomain Service",
    "setup.domain.service_hint": "The service will open in a new tab",
    "setup.domain.duckdns": "Simplest Option",
    "setup.domain.freemyip": "No registration required",
    "setup.domain.dynv6": "More settings available",
    "setup.domain.server": "This server's IP",
    "setup.domain.server_preview": "Demo IP · your server's IP will be here upon installation",
    "setup.domain.label_free": "Assigned address",
    "setup.domain.label_own": "Full panel address",
    "setup.domain.placeholder_free": "my-panel.duckdns.org",
    "setup.domain.placeholder_own": "proxy.example.com",
    "setup.domain.continue": "Continue",
    "setup.domain.note": "Passkey will be bound to this address. Changing it requires reconfiguring access.",
    "setup.dns.progress": "Step 2 of 3 · Address",
    "setup.dns.title": "Set a permanent address",
    "setup.dns.subtitle_free": "Make sure the selected free service points to this IPv4.",
    "setup.dns.subtitle_own": "Open your domain's DNS management and create an A-record with these values.",
    "setup.dns.type": "Record type",
    "setup.dns.name": "Full Address",
    "setup.dns.value": "Server IPv4",
    "setup.dns.copy": "Copy IP",
    "setup.dns.copied": "IP copied",
    "setup.dns.provider_free": "The panel will verify that the free address already points to this server.",
    "setup.dns.provider_own": "Some DNS panels require only the subdomain part of the main domain address.",
    "setup.dns.waiting": "DNS will update shortly—usually within a few minutes, sometimes up to 24 hours",
    "setup.dns.check": "Check Address",
    "setup.dns.checking": "Checking address…",
    "setup.own.record": "Create a record in your DNS panel for this domain",
    "setup.own.record_hint": "If the panel asks only for the name part of the record, enter just the subdomain portion.",
    "setup.own.netlify": "We recommend managing DNS through Netlify",
    "setup.own.netlify_hint": "Add your domain to Netlify and specify the provided Name Servers with your registrar. Managing records there is simple and fast. If your domain already has DNS records, transfer them to Netlify first.",
    "setup.own.netlify_link": "Netlify Instructions",
    "setup.ready.badge": "Address Connected",
    "setup.ready.title": "Secure address ready",
    "setup.ready.subtitle": "DNS is working. The panel will open on the new permanent address where you can continue setting up access and perform all further tasks.",
    "setup.ready.dns": "DNS points to server",
    "setup.ready.tls": "HTTPS certificate active",
    "setup.ready.owner": "A passkey tied to a domain is used for login. If you change domains, it must be registered again.",
    "setup.ready.continue": "Go to Access Setup",
    "onboarding.story.badge": "Installation complete",
    "onboarding.story.title": "Your server is ready",
    "onboarding.story.subtitle": "Connect friends and family without getting into Linux, configs, or terminal commands.",
    "onboarding.story.updates": "Live client auto-updates",
    "onboarding.story.device": "One managed connection link",
    "onboarding.badge": "Initial setup",
    "onboarding.welcome.title": "Access Setup",
    "onboarding.welcome.subtitle": "Configure secure access to the panel. No personal data required.",
    "onboarding.welcome.profile": "Owner only login",
    "onboarding.welcome.profile_hint": "Other users don't need accounts or passwords.",
    "onboarding.welcome.passkey": "Passwordless login",
    "onboarding.welcome.passkey_hint": "Passkeys are stored on your device and secured by the system.",
    "onboarding.welcome.control": "Everything stays under control",
    "onboarding.welcome.control_hint": "Connections, routes, and traffic usage visible in one place.",
    "onboarding.access.create": "Set up access",
    "onboarding.progress.passkey": "Step 2 of 2 · Login protection",
    "onboarding.back": "Back",
    "onboarding.passkey.title": "Login protection",
    "onboarding.passkey.subtitle": "Create a passkey for login instead of a password. You don't need to invent or remember it: it's stored on your device and never sent to the server.",
    "onboarding.passkey.system": "System window will open",
    "onboarding.passkey.system_hint": "Confirm creation with Touch ID, Face ID, or device code.",
    "onboarding.button": "Create passkey",
    "onboarding.passkey.wait": "Waiting for system...",
    "onboarding.secure": "Your passkey is stored in a device key bundle and only works over HTTPS.",
    "loading": "Loading state...",
    "error": "Something went wrong",
    "logout": "Logout"
  },
  "zh-CN": {
    "app.name": "Outpost",
    "title.setup": "初始设置",
    "title.onboarding": "接入配置",
    "title.login": "登录",
    "title.access": "访问",
    "title.settings": "面板设置",
    "title.settings_short": "设置",
    "title.overview": "概览",
    "error.request": "请求未执行",
    "error.http": "服务器暂时不可用（HTTP {status}）",
    "settings.certificate.until": "至 {date}",
    "settings.update.check": "检查",
    "settings.update.upgrade": "更新",
    "settings.update.retry": "重试",
    "settings.update.loading": "正在准备…",
    "settings.update.working": "正在更新…",
    "settings.update.checking": "正在检查更新…",
    "settings.update.preparing": "正在下载并验证签名…",
    "settings.update.confirm": "确认安装此版本。",
    "settings.update.whats_new": "版本 {version} 的新增内容",
    "settings.update.notes_fallback": "修复和改进，暂无单独说明。",
    "settings.update.installing": "正在安装版本 {version}…",
    "settings.update.restarting": "正在重启服务器并验证版本 {version}…",
    "settings.update.completed": "更新已安装",
    "settings.update.failed": "无法安装更新",
    "settings.update.current": "已安装最新版本",
    "settings.update.available": "版本 {version} 可用",
    "settings.update.unchecked": "尚未检查更新",
    "settings.update.channel": "更新通道",
    "settings.update.channel_hint": "稳定版本或预发布候选版本",
    "settings.update.channel.stable": "稳定版本",
    "settings.update.channel.candidate": "发布候选版本",
    "settings.update.restart_wait": "更新后服务器未能在预期时间内恢复",
    "operation.update_verifying": "正在验证更新签名和内容…",
    "operation.update_snapshotting": "正在创建数据快照…",
    "operation.update_installing": "正在安装新版本…",
    "operation.update_restarting": "正在重启 Outpost…",
    "operation.update_readiness": "正在检查新版本是否就绪…",
    "nav.home": "首页",
    "nav.connections": "连接",
    "nav.routes": "路由",
    "nav.protocols": "协议",
    "role.owner": "所有者",
    "action.addConnection": "新建连接",
    "action.add": "添加",
    "action.cancel": "取消",
    "action.save": "保存",
    "action.publish": "发布",
    "action.copy": "复制链接",
    "action.close": "关闭",
    "action.restart": "重启",
    "action.confirm": "确认",
    "connections.title": "连接",
    "connections.subtitle": "连接、流量和活跃度",
    "connections.empty": "暂无连接。创建第一个。",
    "connections.name": "名称",
    "home.connections": "连接",
    "overview.title": "概览",
    "overview.subtitle": "系统运行状态与网络使用情况",
    "overview.users": "用户",
    "overview.events": "最近事件",
    "home.infrastructure": "基础设施",
    "home.works": "已就绪",
    "home.online": "在线",
    "routes.title": "路由",
    "routes.subtitle": "确定哪些服务直接访问、通过代理或已被阻止",
    "routes.add": "添加规则",
    "routes.draft": "存在未发布的更改",
    "routes.published": "所有更改已发布",
    "routes.revision": "发布的修订版",
    "routes.action": "操作",
    "routes.matcher": "类型",
    "routes.value": "域名、网络或列表",
    "routes.system": "系统级",
    "routes.user": "用户级",
    "routes.direct": "直接访问",
    "routes.proxy": "通过代理",
    "routes.block": "阻止",
    "system.log": "日志",
    "journal.eyebrow": "系统",
    "journal.title": "日志",
    "journal.subtitle": "服务器事件和面板变更",
    "journal.search": "搜索日志",
    "system.active": "运行中",
    "system.unknown": "状态未知",
    "engines.eyebrow": "系统",
    "engines.title": "协议",
    "engines.subtitle": "连接技术、版本和配置",
    "engines.healthy": "两个引擎运行正常",
    "engines.attention": "一个引擎需要关注",
    "engines.engine": "引擎",
    "engines.state": "状态",
    "engines.version": "版本",
    "engines.connection": "连接",
    "engines.configuration": "配置",
    "engines.actions": "操作",
    "engines.configure": "设置",
    "engines.updates": "引擎更新",
    "engines.pinned": "锁定版本以确保稳定性",
    "engines.integrity": "SHA-256 完整性检查",
    "engines.no_updates": "无可用更新",
    "engines.updates_available": "有可用更新",
    "engines.current_versions": "使用最新版本的软件",
    "engines.checked": "刚刚验证过版本信息",
    "engines.check": "检查版本",
    "engines.checking": "正在检查...",
    "engines.recent": "最近配置",
    "engines.baseline": "基线配置",
    "engines.published": "已发布",
    "engines.history": "打开历史记录",
    "engines.history_title": "配置历史",
    "engines.history_hint": "最近发布的 Hysteria 2 和 Xray 版本。",
    "engines.history_empty": "暂无用户自定义版本——使用基础配置。",
    "engines.note": "更改将首先进行检查，然后在出错时自动回滚并应用。",
    "auth.badge": "所有者面板",
    "auth.title": "欢迎回来",
    "auth.subtitle": "请使用 Touch ID、Face ID 或此设备的代码进行身份验证。",
    "auth.button": "继续（passkey）",
    "auth.wait": "等待确认…",
    "auth.secure": "Passkey 不发送至服务器，仅保留在您设备的密钥对中。",
    "auth.recovery.title": "无法访问 passkey？",
    "auth.recovery.subtitle": "在服务器上执行恢复命令。它将结束当前会话并生成新的临时链接。",
    "auth.story.badge": "个人空间",
    "auth.story.title": "自己的服务器，自己的规则。",
    "auth.story.subtitle": "在一个宁静的面板中管理亲人的连接、路由和流量。",
    "auth.story.transfer": "将配置迁移到其他服务器",
    "auth.story.protocols": "支持 Xray 和 Hysteria 2",
    "auth.story.clients": "轻松连接客户端",
    "auth.story.web": "所有管理均通过 Web 界面进行",
    "auth.story.speed": "高速度，无额外负载",
    "auth.host": "面板地址",
    "auth.host.copy": "复制面板地址",
    "auth.host.copied": "已复制面板地址",
    "setup.story.badge": "服务器已安装",
    "setup.story.title": "首次启动",
    "setup.story.subtitle": "只需选择固定 IP。无需购买域名——可使用免费服务。",
    "setup.story.running": "Outpost 正在运行",
    "setup.story.secure": "临时 HTTPS 连接已加密",
    "setup.story.browser": "后续所有配置均在浏览器中完成",
    "setup.host": "临时地址",
    "setup.badge": "准备管理面板",
    "setup.configured.badge": "初始设置已完成",
    "setup.configured.title": "此服务器已配置",
    "setup.configured.done": "如果配置由您完成，请使用您选择的永久面板地址。",
    "setup.configured.warning": "如果您是此 VPS 的所有者但未配置 Outpost，可能是其他人完成了配置。",
    "setup.configured.action": "请通过托管服务商控制面板重装 VPS，再次安装 Outpost，并立即打开此地址。重装会删除服务器上的数据。",
    "setup.domain.title": "连接域名",
    "setup.domain.subtitle": "选择如何为 Outpost 获取永久访问地址。",
    "setup.domain.free": "免费子域",
    "setup.domain.free_hint": "基于免费 DNS 服务的子域",
    "setup.domain.free_detail": "Outpost 可免费提供独立子域，无需购买自有域名。",
    "setup.domain.recommended": "推荐",
    "setup.domain.own": "自有域名",
    "setup.domain.own_hint": "受您控制的付费域名",
    "setup.domain.own_detail": "您可以在已购买的域上创建一个专门用于 Outpost 面板的子域名。",
    "setup.configure.progress": "第 2/3 步 · 地址",
    "setup.free.title": "免费子域名",
    "setup.free.subtitle": "选择提供免费子域名的服务。创建地址时请指定服务器 IP，并将结果粘贴到下方。",
    "setup.own.title": "连接自有域名",
    "setup.own.subtitle": "为 Outpost 面板选择一个子域名——例如 proxy.example.com。然后为其创建一个 A 记录。",
    "setup.domain.service": "选择免费子域名服务商",
    "setup.domain.service_hint": "服务将在新标签页中打开",
    "setup.domain.duckdns": "最简单的选项",
    "setup.domain.freemyip": "无需注册",
    "setup.domain.dynv6": "更多设置",
    "setup.domain.server": "此服务器 IP 地址",
    "setup.domain.server_preview": "演示 IP · 安装时将显示您的服务器 IP",
    "setup.domain.label_free": "获取的地址",
    "setup.domain.label_own": "完整面板地址",
    "setup.domain.placeholder_free": "my-panel.duckdns.org",
    "setup.domain.placeholder_own": "proxy.example.com",
    "setup.domain.continue": "继续",
    "setup.domain.note": "Passkey 将绑定到此地址。更换后需重新配置登录。",
    "setup.dns.progress": "步骤 2/3 · 地址",
    "setup.dns.title": "配置固定地址",
    "setup.dns.subtitle_free": "请确保所选免费 DNS 服务已将该 IPv4 指向此服务器。",
    "setup.dns.subtitle_own": "打开您域名的 DNS 管理面板，并创建一条 A 记录以包含这些值。",
    "setup.dns.type": "记录类型",
    "setup.dns.name": "完整地址",
    "setup.dns.value": "IPv4 服务器",
    "setup.dns.copy": "复制 IP",
    "setup.dns.copied": "IP 已复制",
    "setup.dns.provider_free": "面板将检查免费 DNS 是否已将此域名指向该服务器。",
    "setup.dns.provider_own": "某些 DNS 面板要求仅填写部分地址至主域名。",
    "setup.dns.waiting": "DNS 不会立即更新——通常需要几分钟，有时长达一天",
    "setup.dns.check": "检查地址",
    "setup.dns.checking": "正在检查地址…",
    "setup.own.record": "在域名的 DNS 面板中创建记录",
    "setup.own.record_hint": "如果面板仅要求填写名称部分，请提供至主域名的一部分。",
    "setup.own.netlify": "我们推荐通过 Netlify 管理 DNS",
    "setup.own.netlify_hint": "将域名添加到 Netlify，并在注册商处指定提供的 Netlify name servers。在那里管理记录简单快捷。如果域名的 DNS 记录已存在，请先将其迁移到 Netlify。",
    "setup.own.netlify_link": "Netlify 说明文档",
    "setup.ready.badge": "地址已连接",
    "setup.ready.title": "安全地址已就绪",
    "setup.ready.subtitle": "DNS 运行正常。面板将在新的固定地址打开，继续进行访问设置及后续所有操作。",
    "setup.ready.dns": "DNS 指向服务器",
    "setup.ready.tls": "HTTPS 证书有效",
    "setup.ready.owner": "登录使用绑定到域名的 passkey。更换域名后需重新注册它。",
    "setup.ready.continue": "前往访问配置",
    "onboarding.story.badge": "安装完成",
    "onboarding.story.title": "您的服务器已就绪",
    "onboarding.story.subtitle": "无需深入 Linux、配置文件和命令行即可连接亲友。",
    "onboarding.story.updates": "客户端实时自动更新",
    "onboarding.story.device": "一个受控的连接链接",
    "onboarding.badge": "初始设置",
    "onboarding.welcome.title": "访问配置",
    "onboarding.welcome.subtitle": "配置面板的安全登录。无需个人数据。",
    "onboarding.welcome.profile": "仅限所有者登录",
    "onboarding.welcome.profile_hint": "其他用户不需要账户或密码。",
    "onboarding.welcome.passkey": "无密码登录",
    "onboarding.welcome.passkey_hint": "Passkey 存储于您的设备中并由系统保护。",
    "onboarding.welcome.control": "一切尽在掌控之中",
    "onboarding.welcome.control_hint": "连接、路由和流量消耗均在同一处可见。",
    "onboarding.access.create": "设置登录方式",
    "onboarding.progress.passkey": "步骤 2/2 · 登录保护",
    "onboarding.back": "返回",
    "onboarding.passkey.title": "登录保护",
    "onboarding.passkey.subtitle": "使用 passkey 代替密码进行登录。无需自行创建或记忆：它存储于您的设备中，不会发送至服务器。",
    "onboarding.passkey.system": "将弹出系统窗口",
    "onboarding.passkey.system_hint": "通过 Touch ID、Face ID 或设备代码确认创建。",
    "onboarding.button": "创建 passkey",
    "onboarding.passkey.wait": "等待系统...",
    "onboarding.secure": "通行密钥存储在设备密钥对中，仅通过 HTTPS 工作。",
    "loading": "正在加载状态...",
    "error": "发生错误",
    "logout": "退出"
  },
  "fa": {
    "app.name": "Outpost",
    "title.setup": "تنظیم اولیه",
    "title.onboarding": "دسترسی به پنل",
    "title.login": "ورود",
    "title.access": "دسترسی",
    "title.settings": "تنظیمات پنل",
    "title.settings_short": "تنظیمات",
    "title.overview": "مشاهده کلیه موارد",
    "error.request": "درخواست انجام نشد",
    "error.http": "سرور موقتاً در دسترس نیست (HTTP {status})",
    "settings.certificate.until": "تا {date}",
    "settings.update.check": "بررسی",
    "settings.update.upgrade": "به‌روزرسانی",
    "settings.update.retry": "تلاش دوباره",
    "settings.update.loading": "در حال آماده‌سازی…",
    "settings.update.working": "در حال به‌روزرسانی…",
    "settings.update.checking": "در حال بررسی به‌روزرسانی…",
    "settings.update.preparing": "در حال بارگیری و تأیید امضا…",
    "settings.update.confirm": "نصب این نسخه را تأیید کنید.",
    "settings.update.whats_new": "تغییرات نسخهٔ {version}",
    "settings.update.notes_fallback": "رفع اشکال‌ها و بهبودها بدون توضیح جداگانه.",
    "settings.update.installing": "در حال نصب نسخهٔ {version}…",
    "settings.update.restarting": "در حال راه‌اندازی مجدد سرور و بررسی نسخهٔ {version}…",
    "settings.update.completed": "به‌روزرسانی نصب شد",
    "settings.update.failed": "نصب به‌روزرسانی انجام نشد",
    "settings.update.current": "آخرین نسخه نصب است",
    "settings.update.available": "نسخهٔ {version} در دسترس است",
    "settings.update.unchecked": "هنوز به‌روزرسانی‌ها بررسی نشده‌اند",
    "settings.update.channel": "کانال به‌روزرسانی",
    "settings.update.channel_hint": "نسخه‌های پایدار یا نامزدهای پیش‌انتشار",
    "settings.update.channel.stable": "نسخه‌های پایدار",
    "settings.update.channel.candidate": "نامزدهای انتشار",
    "settings.update.restart_wait": "سرور پس از به‌روزرسانی در زمان مورد انتظار بازنگشت",
    "operation.update_verifying": "در حال بررسی امضا و محتوای به‌روزرسانی…",
    "operation.update_snapshotting": "در حال ایجاد snapshot داده‌ها…",
    "operation.update_installing": "در حال نصب نسخهٔ جدید…",
    "operation.update_restarting": "در حال راه‌اندازی مجدد Outpost…",
    "operation.update_readiness": "در حال بررسی آماده بودن نسخهٔ جدید…",
    "nav.home": "خانه",
    "nav.connections": "اتصالات",
    "nav.routes": "مسیرها",
    "nav.protocols": "پروتکل‌ها",
    "role.owner": "مالک",
    "action.addConnection": "اتصال جدید",
    "action.add": "افزودن",
    "action.cancel": "لغو",
    "action.save": "ذخیره",
    "action.publish": "انتشار",
    "action.copy": "لینک را کپی کنید",
    "action.close": "بستن",
    "action.restart": "راه‌اندازی مجدد",
    "action.confirm": "تایید",
    "connections.title": "اتصالات",
    "connections.subtitle": "لینک، ترافیک و فعالیت اتصالات",
    "connections.empty": "هنوز اتصال وجود ندارد. اولین خود را بسازید.",
    "connections.name": "نام",
    "home.connections": "اتصالات",
    "overview.title": "خانه",
    "overview.subtitle": "وضعیت سیستم و استفاده از شبکه",
    "overview.users": "کاربران",
    "overview.events": "آخرین رویدادها",
    "home.infrastructure": "ساختار زیربنایی",
    "home.works": "در حال کار است",
    "home.online": "آنلاین",
    "routes.title": "مسیرها",
    "routes.subtitle": "تعیین کنید کدام سرویس‌ها مستقیماً، از طریق پروکسی یا مسدود می‌شوند",
    "routes.add": "افزودن قانون",
    "routes.draft": "تغییرات غیرمنتشره وجود دارد",
    "routes.published": "همه تغییرات منتشر شدند",
    "routes.revision": "نسخه انتشار یافته",
    "routes.action": "عملکرد",
    "routes.matcher": "نوع",
    "routes.value": "دامنه، شبکه یا لیست",
    "routes.system": "سیستمی",
    "routes.user": "کاربردی",
    "routes.direct": "مستقیم",
    "routes.proxy": "از طریق پروکسی",
    "routes.block": "مسدود کردن",
    "system.log": "روزنامه",
    "journal.eyebrow": "سیستم",
    "journal.title": "روزنامه",
    "journal.subtitle": "رویدادها و تغییرات پنل سرور",
    "journal.search": "جستجو در روزنامه",
    "system.active": "فعال است",
    "system.unknown": "وضعیت ناشناخته",
    "engines.eyebrow": "سیستم",
    "engines.title": "پروتکل‌ها",
    "engines.subtitle": "تکنولوژی‌ها، نسخه‌ها و تنظیمات اتصال",
    "engines.healthy": "هر دو موتور سالم هستند",
    "engines.attention": "یکی از موتورها نیاز به توجه دارد",
    "engines.engine": "موتور",
    "engines.state": "وضعیت",
    "engines.version": "نسخه",
    "engines.connection": "اتصال",
    "engines.configuration": "پیکربندی",
    "engines.actions": "اقدامات",
    "engines.configure": "تنظیم کنید",
    "engines.updates": "به‌روزرسانی موتورها",
    "engines.pinned": "نسخه‌های قفل شده برای پایداری",
    "engines.integrity": "بررسی سلامت SHA-256",
    "engines.no_updates": "به‌روزرسانی موجود نیست",
    "engines.updates_available": "به‌روزرسانی‌ها در دسترس هستند",
    "engines.current_versions": "از نسخه‌های به‌روز استفاده می‌شود",
    "engines.checked": "نسخه‌ها اخیراً بررسی شدند",
    "engines.check": "بررسی نسخه‌ها",
    "engines.checking": "در حال بررسی...",
    "engines.recent": "آخرین تنظیمات",
    "engines.baseline": "تنظیمات پایه",
    "engines.published": "انتشار یافته",
    "engines.history": "تاریخچه باز شود",
    "engines.history_title": "تاریخچه تنظیمات",
    "engines.history_hint": "آخرین نسخه‌های منتشر شده Hysteria 2 و Xray.",
    "engines.history_empty": "هنوز هیچ نسخه کاربری وجود ندارد - از تنظیمات پایه استفاده می‌شود.",
    "engines.note": "ابتدا تغییرات بررسی می‌شوند، سپس با بازگشت خودکار در صورت خطا اعمال می‌گردند.",
    "auth.badge": "پنل مالک",
    "auth.title": "به امید دیدار",
    "auth.subtitle": "ورود را با Touch ID، Face ID یا این passkey تایید کنید.",
    "auth.button": "ادامه با passkey",
    "auth.wait": "در انتظار تایید...",
    "auth.secure": "Passkey به سرور ارسال نمی‌شود و در کلیدهای دستگاه شما باقی می‌ماند.",
    "auth.recovery.title": "دسترسی به passkey ندارید؟",
    "auth.recovery.subtitle": "اجرای دستور بازیابی روی سرور را انجام دهید. این عمل سشن‌های فعال را خاتمه داده و یک لینک تک‌بارمصرف جدید ارائه خواهد کرد.",
    "auth.story.badge": "فضای شخصی",
    "auth.story.title": "سرور خود، قوانین خود.",
    "auth.story.subtitle": "مدیریت اتصال نزدیکان، مسیرها و ترافیک از طریق یک پنل آرامش‌بخش.",
    "auth.story.transfer": "انتقال تنظیمات به سرور دیگر",
    "auth.story.protocols": "پشتیبانی از Xray و Hysteria 2",
    "auth.story.clients": "اتصال سبک مشتریان",
    "auth.story.web": "تمام مدیریت از طریق رابط وب",
    "auth.story.speed": "سرعت بالا بدون بار اضافی",
    "auth.host": "آدرس پنل",
    "auth.host.copy": "کپی کردن آدرس پنل",
    "auth.host.copied": "آدرس کپی شد",
    "setup.story.badge": "سرور نصب شده",
    "setup.story.title": "اجرای اولیه",
    "setup.story.subtitle": "باقیده انتخاب یک آدرس ثابت. خرید دامنه الزامی نیست - می‌توانید از رایگان استفاده کنید.",
    "setup.story.running": "Outpost اجرا شده",
    "setup.story.secure": "اتصال امنیتی HTTPS موقت",
    "setup.story.browser": "در مرورگر ادامه دهید و تنظیمات را انجام دهید",
    "setup.host": "آدرس موقت",
    "setup.badge": "آماده‌سازی پنل",
    "setup.configured.badge": "تنظیم اولیه تکمیل شده است",
    "setup.configured.title": "این سرور از قبل تنظیم شده است",
    "setup.configured.done": "اگر تنظیم را خودتان انجام داده‌اید، از آدرس دائمی انتخاب‌شده برای پنل استفاده کنید.",
    "setup.configured.warning": "اگر مالک این VPS هستید اما Outpost را تنظیم نکرده‌اید، ممکن است شخص دیگری این کار را انجام داده باشد.",
    "setup.configured.action": "VPS را از پنل شرکت میزبان دوباره نصب کنید، Outpost را مجدداً نصب کنید و فوراً این آدرس را باز کنید. نصب مجدد داده‌های سرور را حذف می‌کند.",
    "setup.domain.title": "ارتباط با دامنه",
    "setup.domain.subtitle": "انتخاب کنید چگونه آدرس دائمی برای پنل Outpost دریافت می‌کنید.",
    "setup.domain.free": "زیردامنه رایگان",
    "setup.domain.free_hint": "در سرویس DNS رایگان",
    "setup.domain.free_detail": "برای پنل Outpost می‌توانید بدون خرید دامنه، یک زیردامنه مجزا به صورت رایگان دریافت کنید.",
    "setup.domain.recommended": "پیشنهادی",
    "setup.domain.own": "دامنه شخصی",
    "setup.domain.own_hint": "دومین پولی تحت کنترل خودتان",
    "setup.domain.own_detail": "می‌توانید روی یک دومین خریداری شده، زیردامنه‌ای جداگانه مخصوص پنل Outpost ایجاد کنید.",
    "setup.configure.progress": "مرحله ۲ از ۳ · آدرس",
    "setup.free.title": "زیردامنه رایگان",
    "setup.free.subtitle": "یک سرویس ارائه دهنده زیردامنه رایگان را انتخاب کنید. هنگام ساخت، آی‌پی سرور را وارد کرده و نتیجه را در کادر پایین قرار دهید.",
    "setup.own.title": "اتصال به دومین شخصی خود",
    "setup.own.subtitle": "زیردامنی برای پنل Outpost را انتخاب کنید - مثلاً proxy.example.com. سپس یک رکورد A برای آن بسازید.",
    "setup.domain.service": "سرویس زیردامنه‌های رایگان را انتخاب کنید",
    "setup.domain.service_hint": "این سرویس در تب جدید باز می‌شود",
    "setup.domain.duckdns": "سادگی ترین گزینه",
    "setup.domain.freemyip": "بدون ثبت‌نام",
    "setup.domain.dynv6": "تنظیمات بیشتر",
    "setup.domain.server": "آی‌پی این سرور",
    "setup.domain.server_preview": "آی‌پی دمو · در حین نصب آی‌پی سرور شما اینجا قرار می‌گیرد",
    "setup.domain.label_free": "آدرس دریافت شده",
    "setup.domain.label_own": "آدرس کامل پنل",
    "setup.domain.placeholder_free": "my-panel.duckdns.org",
    "setup.domain.placeholder_own": "proxy.example.com",
    "setup.domain.continue": "ادامه",
    "setup.domain.note": "کلید عبور به این آدرس متصل می‌شود. در صورت تغییر، نیاز است مجدداً تنظیم شود.",
    "setup.dns.progress": "مرحله 2 از 3 · آدرس",
    "setup.dns.title": "تنظیم یک آدرس ثابت",
    "setup.dns.subtitle_free": "اطمینان حاصل کنید که در سرویس رایگان انتخاب شده برای آدرس، این IPv4 ذکر شده است.",
    "setup.dns.subtitle_own": "مدیریت DNS دامنه خود را باز کرده و یک رکورد A با این مقادیر ایجاد کنید.",
    "setup.dns.type": "نوع رکورد",
    "setup.dns.name": "آدرس کامل",
    "setup.dns.value": "سرور IPv4",
    "setup.dns.copy": "کپی کردن IP",
    "setup.dns.copied": "IP کپی شد",
    "setup.dns.provider_free": "پنل بررسی خواهد کرد که آیا آدرس رایگان قبلاً به این سرور اشاره میکند یا خیر.",
    "setup.dns.provider_own": "برخی پنل‌های DNS فقط بخشی از آدرس را درخواست می‌کنند، نه کل آن نسبت به دامنه اصلی.",
    "setup.dns.waiting": "DNS بلافاصله آپدیت نمی‌شود — معمولاً چند دقیقه طول می‌کشد و گاهی تا یک روز",
    "setup.dns.check": "بررسی آدرس",
    "setup.dns.checking": "در حال بررسی آدرس…",
    "setup.own.record": "یک رکورد در پنل DNS دامنه ایجاد کنید",
    "setup.own.record_hint": "اگر پنل فقط نام رکورد را درخواست می‌کند، بخشی از آدرس نسبت به دامنه اصلی را وارد کنید.",
    "setup.own.netlify": "پیشنهاد می‌کنیم مدیریت DNS را از طریق Netlify انجام دهید",
    "setup.own.netlify_hint": "دامنه خود را در Netlify اضافه کرده و name servers ارائه شده توسط Netlify را برای ثبت‌کارگر تنظیم کنید. مدیریت رکوردها آنجا ساده و سریع است. اگر دامنه شما قبلاً دارای رکوردهای DNS باشد، ابتدا آنها را به Netlify منتقل کنید.",
    "setup.own.netlify_link": "راهنمای Netlify",
    "setup.ready.badge": "آدرس متصل شد",
    "setup.ready.title": "آدرس محافظه‌شده آماده است",
    "setup.ready.subtitle": "DNS فعال است. پنل در آدرس ثابت جدید باز می‌شود - آنجا ادامه تنظیمات دسترسی و تمام کارهای بعدی انجام خواهد شد.",
    "setup.ready.dns": "DNS به سرور اشاره دارد",
    "setup.ready.tls": "سرمای HTTPS فعال است",
    "setup.ready.owner": "برای ورود از passkey استفاده می‌شود که به دامنه متصل شده. در صورت تغییر دامنه، باید مجدداً ثبت شود.",
    "setup.ready.continue": "به تنظیمات دسترسی بروید",
    "onboarding.story.badge": "نصب تمام شد",
    "onboarding.story.title": "سرور شما آماده است",
    "onboarding.story.subtitle": "دوستان و نزدیکان را بدون غوطه‌وری در Linux، کانفیگ‌ها و دستورات ترمینال متصل کنید.",
    "onboarding.story.updates": "به‌روزرسانی خودکار کلاینت‌ها",
    "onboarding.story.device": "یک لینک قابل مدیریت برای اتصال",
    "onboarding.badge": "تنظیمات اولیه",
    "onboarding.welcome.title": "دسترسی به پنل",
    "onboarding.welcome.subtitle": "ورودی امن را تنظیم کنید. اطلاعات شخصی مورد نیاز نیست.",
    "onboarding.welcome.profile": "فقط مالک اجازه ورود دارد",
    "onboarding.welcome.profile_hint": "کاربران دیگر نیازی به حساب یا رمز عبور ندارند.",
    "onboarding.welcome.passkey": "ورود بدون رمز عبور",
    "onboarding.welcome.passkey_hint": "Passkey روی دستگاه شما ذخیره شده و توسط سیستم محافظت می‌شود.",
    "onboarding.welcome.control": "همه چیز تحت کنترل است",
    "onboarding.welcome.control_hint": "اتصالات، مسیرها و مصرف ترافیک در یک مکان قابل مشاهده هستند.",
    "onboarding.access.create": "تنظیم ورود",
    "onboarding.progress.passkey": "مرحله ۲ از ۲ · امنیت ورود",
    "onboarding.back": "بازگشت",
    "onboarding.passkey.title": "امنیت ورود",
    "onboarding.passkey.subtitle": "برای جایگزینی رمز عبور، یک passkey برای ورود ایجاد کنید. نیازی به اختراع یا حفظ آن نیست: روی دستگاه شما ذخیره می‌شود و به سرور ارسال نمی‌گردد.",
    "onboarding.passkey.system": "پنجره سیستمی باز خواهد شد",
    "onboarding.passkey.system_hint": "ایجاد را با استفاده از Touch ID، Face ID یا کد دستگاه تأیید کنید.",
    "onboarding.button": "ساخت passkey",
    "onboarding.passkey.wait": "در انتظار سیستم...",
    "onboarding.secure": "کلید عبور در بسته‌ی کلیدهای دستگاه ذخیره می‌شود و تنها از طریق HTTPS کار می‌کند.",
    "loading": "در حال بارگذاری وضعیت...",
    "error": "مشکلی پیش آمد",
    "logout": "خروج"
  }
} as const;
